import { notFound } from "next/navigation";
import Link from "next/link";
import { getOwnedFiling } from "@/lib/session";
import { prisma } from "@/lib/prisma";
import { PrintButton } from "./PrintButton";

export const dynamic = "force-dynamic";

// Printable proof-of-filing page. Customers reach this from the
// FilingStatusBanner once status === CONFIRMED. The print stylesheet is
// inlined below so they can Cmd/Ctrl-P → Save as PDF for their tax records.
export default async function FilingConfirmationPage({ params }: { params: { id: string } }) {
  const owned = await getOwnedFiling(params.id);
  if (!owned) notFound();

  const filing = await prisma.filing.findUnique({ where: { id: owned.id } });
  if (!filing) notFound();

  const isDelivered = filing.status === "CONFIRMED";

  return (
    <div className="max-w-2xl mx-auto px-6 py-10">
      {/* On-screen header — hidden when printing */}
      <div className="print:hidden mb-6 flex items-center justify-between">
        <Link href={`/filings/${filing.id}`} className="text-sm text-slate-500 hover:underline">
          ← Back to filing
        </Link>
        <PrintButton />
      </div>

      {/* Printable card */}
      <div className="bg-white border border-slate-200 rounded-lg p-8 print:border-0 print:p-0">
        <div className="flex items-center justify-between mb-8 pb-6 border-b border-slate-200">
          <div className="text-lg font-semibold">
            <span className="text-slate-900">Form</span>
            <span className="text-blue-900">5472</span>
            <span className="text-slate-900"> Prep</span>
          </div>
          <div className="text-xs uppercase tracking-wider text-slate-500 font-medium">
            Proof of submission
          </div>
        </div>

        <h1 className="text-2xl font-semibold text-slate-900 mb-2">
          {isDelivered ? "Filing delivered to the IRS" : "Filing in progress"}
        </h1>
        <p className="text-slate-600 mb-8">
          {isDelivered
            ? "This document confirms that the Form 5472 + pro forma Form 1120 detailed below was successfully transmitted to the IRS Ogden PIN Unit via fax."
            : "This filing has not yet been delivered. Return to your portal for the latest status."}
        </p>

        <dl className="space-y-3 text-sm border-t border-slate-200 pt-6">
          <Row label="Filing ID" value={filing.id} mono />
          <Row label="LLC" value={filing.llcName} />
          <Row label="EIN" value={filing.llcEin} mono />
          <Row label="Tax year(s)" value={filing.taxYears.join(", ")} />
          <Row
            label="Filing type"
            value={
              filing.isDiirsp
                ? "Delinquent International Information Return Submission Procedures (DIIRSP)"
                : "Form 5472 + pro forma Form 1120"
            }
          />
          <Row label="Foreign owner" value={filing.ownerName} />
          <Row label="Owner country" value={filing.ownerCountryTaxResidence} />
          <Row label="Faxed to" value="IRS Ogden PIN Unit · +1 855-887-7737" />
          <Row label="Fax job ID" value={filing.faxJobId} mono />
          <Row label="Status" value={filing.status} />
          {isDelivered && <Row label="Delivered" value={filing.updatedAt.toLocaleString()} />}
        </dl>

        <div className="mt-8 pt-6 border-t border-slate-200 text-xs text-slate-500 leading-relaxed">
          <p className="mb-2">
            <strong className="text-slate-700">Note:</strong> The IRS does not issue acknowledgments
            for faxed Form 5472 submissions. This document, together with the timestamp on the fax
            transmission record, serves as your contemporaneous evidence of filing.
          </p>
          <p>
            Retain this confirmation with your tax records. Generated by Form5472 Prep on{" "}
            {new Date().toLocaleDateString()}.
          </p>
        </div>
      </div>
    </div>
  );
}

function Row({ label, value, mono }: { label: string; value: string | null | undefined; mono?: boolean }) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-1 sm:gap-4">
      <dt className="text-slate-500 text-xs uppercase tracking-wider sm:text-sm sm:normal-case sm:tracking-normal">{label}</dt>
      <dd className={`sm:col-span-2 text-slate-900 break-words ${mono ? "font-mono text-xs" : ""}`}>
        {value && value.trim().length > 0 ? value : <span className="text-slate-400">—</span>}
      </dd>
    </div>
  );
}
