"use client";

import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";

const STATUSES = [
  "DRAFT",
  "PAID",
  "PDF_GENERATED",
  "SIGNATURE_PENDING",
  "SIGNED_UPLOADED",
  "FAXED",
  "CONFIRMED",
  "FAILED",
];

type Props = {
  filingId: string;
  currentStatus: string;
  userEmail: string | null;
  hasFaxService: boolean;
  hasSignedPdf: boolean;
  hasGeneratedPdf: boolean;
  hasCustomerSignature: boolean;
  hasFaxedPdf: boolean;
  // A stored IRS fax transmission receipt (faxConfirmationKey).
  hasFaxReceipt: boolean;
  // Fax delivery confirmed (receipt on file, or CONFIRMED with a fax job) —
  // shows the "Resend fax confirmation" button. Same rule the server uses.
  canResendFaxConfirmation: boolean;
  preflightStatus: string | null;
  preflightOverrideBy: string | null;
  reviewApprovedAt: string | null;
  reviewApprovedBy: string | null;
  faxedAt: string | null; // ISO string when the fax was sent
};

export function AdminActions({ filingId, currentStatus, userEmail, hasFaxService, hasSignedPdf, hasGeneratedPdf, hasCustomerSignature, hasFaxedPdf, hasFaxReceipt, canResendFaxConfirmation, preflightStatus, preflightOverrideBy, reviewApprovedAt, reviewApprovedBy, faxedAt }: Props) {
  // Confirm before discarding the signed PDF; regen invalidates it because
  // the signature was applied to the old PDF and won't be valid against the
  // freshly generated bytes.
  async function confirmRegenerate(): Promise<boolean> {
    if (!hasSignedPdf) return true;
    return window.confirm(
      "Regenerating will DISCARD the existing signed PDF — the customer (or you) will need to re-sign. Continue?",
    );
  }

  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [uploading, setUploading] = useState<null | "signed" | "reviewed">(null);
  // Reviewed-PDF upload emails the client by default; untick to upload quietly.
  const [notifyClient, setNotifyClient] = useState(true);
  const [status, setStatus] = useState(currentStatus);
  const [msg, setMsg] = useState<{ kind: "ok" | "err"; text: string } | null>(null);
  const [preflightOverrideReason, setPreflightOverrideReason] = useState("");
  // Customer-facing email: keep the button disabled for the whole request so
  // a double-click can't send the confirmation twice.
  const [resendingFaxConfirmation, setResendingFaxConfirmation] = useState(false);
  // Fax: disabled for the whole request (a double click must never fax the IRS
  // twice); the "send again" confirmation is an inline form, and the server's
  // answer is shown right under the fax buttons.
  const [faxing, setFaxing] = useState(false);
  // Synchronous twin of `faxing`: two clicks inside one render both see
  // faxing === false, but not this.
  const faxInFlight = useRef(false);
  const [refaxOpen, setRefaxOpen] = useState(false);
  const [refaxPrompt, setRefaxPrompt] = useState("");
  const [refaxReason, setRefaxReason] = useState("");
  const [faxMsg, setFaxMsg] = useState<{ kind: "ok" | "err"; text: string } | null>(null);

  async function postAction(body: Record<string, unknown>): Promise<ActionResponse> {
    try {
      const res = await fetch(`/api/admin/filings/${filingId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) return { ok: false, ...parseActionError(await res.text(), res.status) };
      const payload = await res.json().catch(() => ({})) as Record<string, unknown>;
      return { ok: true, payload };
    } catch (e) {
      return { ok: false, message: e instanceof Error ? e.message : "Network error" };
    }
  }

  async function callApi(
    body: Record<string, unknown>,
    okMsg: string | ((responseBody: Record<string, unknown>) => string),
  ): Promise<boolean> {
    setMsg(null);
    const result = await postAction(body);
    if (!result.ok) {
      setMsg({ kind: "err", text: result.message });
      return false;
    }
    setMsg({ kind: "ok", text: typeof okMsg === "function" ? okMsg(result.payload) : okMsg });
    startTransition(() => router.refresh());
    return true;
  }

  // withReason: the admin confirmed "send again" in the inline form. Without
  // it the server sends only when no earlier fax can still reach the IRS; if
  // it answers refax_reason_required, the form opens with its explanation.
  async function sendFax(withReason: boolean) {
    if (faxInFlight.current) return;
    faxInFlight.current = true;
    setFaxing(true);
    setFaxMsg(null);
    try {
      const result = await postAction(
        withReason
          ? { action: "retryFax", force: true, reason: refaxReason }
          : { action: "retryFax" },
      );
      if (result.ok) {
        setRefaxOpen(false);
        setRefaxReason("");
        setFaxMsg({ kind: "ok", text: "Fax submitted to IRS ✓" });
        startTransition(() => router.refresh());
        return;
      }
      if (result.code === "refax_reason_required" && !refaxOpen) {
        setRefaxPrompt(result.message);
        setRefaxOpen(true);
        return;
      }
      setFaxMsg({ kind: "err", text: result.message });
    } finally {
      faxInFlight.current = false;
      setFaxing(false);
    }
  }

  // Read a File object as base64 (no data: prefix) so we can post it as JSON.
  // PDFs are small enough (200KB-2MB typical) that this is fine without
  // multipart/streaming.
  function fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        if (typeof result !== "string") return reject(new Error("Unexpected reader result"));
        const comma = result.indexOf(",");
        resolve(comma === -1 ? result : result.slice(comma + 1));
      };
      reader.onerror = () => reject(reader.error ?? new Error("Read failed"));
      reader.readAsDataURL(file);
    });
  }

  async function handleSignedPdfUpload(file: File | undefined) {
    if (!file) return;
    setUploading("signed");
    try {
      if (!file.name.toLowerCase().endsWith(".pdf")) {
        setMsg({ kind: "err", text: "Please pick a .pdf file." });
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        setMsg({ kind: "err", text: `File too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Max 10 MB.` });
        return;
      }
      const pdfBase64 = await fileToBase64(file);
      await callApi(
        { action: "uploadSignedPdf", pdfBase64 },
        `Signed PDF uploaded (${(file.size / 1024).toFixed(0)} KB). Ready to fax.`,
      );
    } catch (e) {
      setMsg({ kind: "err", text: e instanceof Error ? e.message : "Upload failed" });
    } finally {
      setUploading(null);
    }
  }

  async function handleReviewedPdfUpload(file: File | undefined) {
    if (!file) return;
    setUploading("reviewed");
    try {
      if (!file.name.toLowerCase().endsWith(".pdf")) {
        setMsg({ kind: "err", text: "Please pick a .pdf file." });
        return;
      }
      if (
        hasCustomerSignature &&
        !window.confirm(
          notifyClient
            ? "The client has already signed an earlier version. Uploading this reviewed PDF sets that signature aside and emails them to check and sign the new version. Continue?"
            : "The client has already signed an earlier version. Uploading this reviewed PDF sets that signature aside, so they must sign the new version. They will NOT be emailed. Continue?",
        )
      ) {
        return;
      }
      if (file.size > 10 * 1024 * 1024) {
        setMsg({ kind: "err", text: `File too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Max 10 MB.` });
        return;
      }
      const pdfBase64 = await fileToBase64(file);
      await callApi({ action: "uploadReviewedPdf", pdfBase64, notifyClient }, (body) => {
        const size = `${(file.size / 1024).toFixed(0)} KB`;
        if (body.emailSkipped === true) {
          return `Reviewed PDF uploaded (${size}). The client was not emailed. It is ready for them to sign in their portal.`;
        }
        if (body.emailSent === false) {
          const why = typeof body.emailError === "string" && body.emailError.trim()
            ? body.emailError.trim()
            : "Unknown email error";
          return `Reviewed PDF uploaded (${size}), but the client was NOT emailed: ${why}`;
        }
        const to = typeof body.emailTo === "string" ? body.emailTo : userEmail ?? "the client";
        return `Reviewed PDF uploaded (${size}). ${to} has been emailed a link to check and sign it.`;
      });
    } catch (e) {
      setMsg({ kind: "err", text: e instanceof Error ? e.message : "Upload failed" });
    } finally {
      setUploading(null);
    }
  }

  const preflightOverrideReady = preflightOverrideReason.trim().replace(/\s/g, "").length >= 10;
  const preflightAllowsSignature = preflightStatus === "passed" || !!preflightOverrideBy;
  // A fax already went out (in flight or delivered): sending again needs a
  // written reason (the server enforces it too) so the IRS never gets a
  // duplicate by accident.
  const alreadyFaxed = currentStatus === "FAXED" || currentStatus === "CONFIRMED";
  const faxAgainWarning =
    currentStatus === "CONFIRMED"
      ? "This filing was already DELIVERED to the IRS. Faxing again sends the IRS a second copy of the package. Only do this if the IRS asked for it."
      : "A fax for this filing is already on its way or waiting for delivery confirmation. Sending again may give the IRS a duplicate — check Telnyx first.";
  const refaxReasonReady = refaxReasonIsValid(refaxReason);

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row gap-2 sm:items-end">
        <label className="flex-1">
          <span className="block text-xs text-slate-500 mb-1">Override status</span>
          <select
            value={status}
            onChange={(e) => setStatus(e.target.value)}
            disabled={pending || uploading !== null}
            className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white"
          >
            {STATUSES.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </label>
        <button
          type="button"
          onClick={() => callApi({ action: "setStatus", status }, `Status set to ${status}`)}
          disabled={pending || uploading !== null || status === currentStatus}
          className="px-4 py-2 text-sm font-medium bg-slate-900 text-white rounded-md hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save"}
        </button>
      </div>

      {preflightStatus === "failed" && (
        <div className="pt-2 border-t border-slate-100 space-y-2">
          <label className="block">
            <span className="block text-xs font-medium text-slate-600 mb-1">
              Why is this package safe to send?
            </span>
            <textarea
              value={preflightOverrideReason}
              onChange={(e) => setPreflightOverrideReason(e.target.value)}
              disabled={pending || uploading !== null}
              rows={3}
              className="w-full rounded-md border border-slate-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent/30 focus:border-accent disabled:bg-slate-50 disabled:text-slate-400"
            />
          </label>
          <ActionButton
            disabled={pending || uploading !== null || !preflightOverrideReady}
            onClick={async () => {
              const ok = await callApi(
                { action: "approvePreflightOverride", reason: preflightOverrideReason },
                "Pre-flight override recorded. Faxing is enabled.",
              );
              if (ok) setPreflightOverrideReason("");
            }}
            tooltip="Records staff approval to fax a package that failed automated pre-flight checks."
          >
            Approve despite pre-flight failures
          </ActionButton>
        </div>
      )}

      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">Client check &amp; signature</p>
        {reviewApprovedAt ? (
          <p className="text-sm text-emerald-700">
            ✓ Sent to the client to check and sign by {reviewApprovedBy ?? "unknown admin"} at {reviewApprovedAt}.
          </p>
        ) : (
          <p className="text-sm text-slate-500">
            Not sent to the client yet. Upload the reviewed PDF (under &ldquo;Change the package&rdquo;) — that emails the client a link to check it and sign.
          </p>
        )}
        {!preflightAllowsSignature && (
          <p className="text-xs text-amber-700">Pre-flight has failed and no override is recorded — the reviewed PDF can&apos;t be sent yet.</p>
        )}
      </div>

      {/* Sign the package — two paths, pick one:
          (1) In-app placement tool: drop the customer's drawn signature on
              the unsigned PDF via click-to-place. Only available if the
              customer drew their signature in the portal.
          (2) Upload already-signed PDF: the CLIENT signed outside the portal
              (wet-ink scan or their own e-signature) and sent it to us.
          The pro forma 1120 signature is always the owner's own — staff
          never sign it on the client's behalf (owner rule, 2026-10-05). */}
      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">Sign the package</p>
        <div className="flex flex-wrap gap-2">
          {hasCustomerSignature ? (
            <a
              href={`/admin/filings/${filingId}/place-signature`}
              className="inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-accent bg-accent/5 text-accent hover:bg-accent/10"
            >
              Place customer signature →
            </a>
          ) : (
            <span
              title="Customer hasn't drawn their signature in the portal yet"
              className="inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-slate-200 bg-slate-50 text-slate-400 cursor-not-allowed"
            >
              Place customer signature → (no signature yet)
            </span>
          )}
          <label>
            <span
              className={`inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-slate-300 bg-white ${
                pending || uploading !== null ? "opacity-50 cursor-not-allowed" : "hover:bg-slate-50 cursor-pointer"
              }`}
            >
              {uploading === "signed" ? "Uploading signed PDF…" : "Upload already-signed PDF…"}
            </span>
            <input
              type="file"
              accept="application/pdf,.pdf"
              disabled={pending || uploading !== null}
              onChange={(e) => {
                const input = e.currentTarget;
                const file = e.target.files?.[0];
                void handleSignedPdfUpload(file).finally(() => {
                  input.value = "";
                });
              }}
              className="sr-only"
            />
          </label>
        </div>
        <p className="text-xs text-slate-400">
          Only the client signs the Form 1120. Upload a PDF here only if the client signed it themselves outside the portal. It populates{" "}
          <code className="font-mono">signedPdfKey</code> + bumps status to{" "}
          <code className="font-mono">SIGNED_UPLOADED</code> so the fax button enables.
        </p>
      </div>

      {/* Fax submission. Once a fax is out, sending again is a deliberate,
          confirmed step — one click must never give the IRS a duplicate. */}
      {hasFaxService && (
        <div className="pt-2 border-t border-slate-100 space-y-2">
          <p className="text-xs text-slate-500">Fax submission</p>
          {currentStatus === "CONFIRMED" && (
            <p className="text-sm text-emerald-700">
              ✓ Delivered to the IRS{faxedAt ? ` (sent ${formatUtc(faxedAt)})` : ""}.
            </p>
          )}
          {currentStatus === "FAXED" && (
            <p className="text-sm text-slate-700">
              Fax sent{faxedAt ? ` ${formatUtc(faxedAt)}` : ""} — waiting for delivery confirmation.
            </p>
          )}
          {!refaxOpen && (
            <ActionButton
              disabled={pending || uploading !== null || !hasSignedPdf || faxing}
              onClick={() => {
                setFaxMsg(null);
                if (alreadyFaxed) {
                  setRefaxPrompt(faxAgainWarning);
                  setRefaxOpen(true);
                  return;
                }
                void sendFax(false);
              }}
              tooltip={!hasSignedPdf ? "No signed PDF uploaded yet" : undefined}
              primary={!alreadyFaxed}
            >
              {faxing
                ? "Sending fax…"
                : alreadyFaxed
                  ? "Fax again…"
                  : currentStatus === "FAILED"
                    ? "Retry fax"
                    : "Send fax to IRS"}
            </ActionButton>
          )}
          {refaxOpen && (
            <div className="space-y-2 rounded-md border border-amber-300 bg-amber-50 p-3">
              <p className="text-sm text-amber-900">{refaxPrompt}</p>
              <label className="block">
                <span className="mb-1 block text-xs font-medium text-slate-600">
                  Why send this fax again? (at least {REFAX_MIN_REASON_CHARS} characters, saved to the change log)
                </span>
                <textarea
                  value={refaxReason}
                  onChange={(e) => setRefaxReason(e.target.value)}
                  disabled={faxing}
                  rows={3}
                  className="w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/30 disabled:bg-slate-50 disabled:text-slate-400"
                />
              </label>
              <div className="flex flex-wrap gap-2">
                <ActionButton
                  disabled={pending || uploading !== null || !hasSignedPdf || faxing || !refaxReasonReady}
                  onClick={() => void sendFax(true)}
                  tooltip={refaxReasonReady ? undefined : `Write a reason of at least ${REFAX_MIN_REASON_CHARS} characters first`}
                  primary
                >
                  {faxing ? "Sending fax…" : "Send to the IRS again"}
                </ActionButton>
                <ActionButton
                  disabled={faxing}
                  onClick={() => {
                    setRefaxOpen(false);
                    setRefaxReason("");
                    setFaxMsg(null);
                  }}
                >
                  Cancel
                </ActionButton>
              </div>
            </div>
          )}
          {faxMsg && (
            <p
              role={faxMsg.kind === "err" ? "alert" : "status"}
              className={`rounded-md border px-3 py-2 text-sm ${
                faxMsg.kind === "ok"
                  ? "border-emerald-200 bg-emerald-50 text-emerald-800"
                  : "border-red-200 bg-red-50 text-red-800"
              }`}
            >
              {faxMsg.text}
            </p>
          )}
          {!hasSignedPdf && (
            <p className="text-xs text-slate-400">Waiting for customer to upload signed PDF</p>
          )}
        </div>
      )}

      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">Customer emails</p>
        <div className="flex flex-wrap items-center gap-2">
            <ActionButton
              disabled={pending || uploading !== null || !userEmail}
              onClick={() => callApi({ action: "resendOrderConfirmation" }, "Order confirmation resent")}
              tooltip={!userEmail ? "No customer email on file" : undefined}
            >
              Resend order confirmation
            </ActionButton>
            <ActionButton
              disabled={pending || uploading !== null || !userEmail}
              onClick={() => callApi({ action: "resendMagicLink" }, "Magic link resent")}
              tooltip={!userEmail ? "No customer email on file" : undefined}
            >
              Resend magic link
            </ActionButton>
            {canResendFaxConfirmation && (
              <ActionButton
                disabled={pending || uploading !== null || !userEmail || resendingFaxConfirmation}
                onClick={async () => {
                  setResendingFaxConfirmation(true);
                  try {
                    await callApi({ action: "resendFaxConfirmation" }, (body) => {
                      const to = typeof body.to === "string" ? body.to : userEmail ?? "the customer";
                      const receipt =
                        body.receiptAttached === false
                          ? "without a receipt attachment (no receipt PDF is on file)"
                          : "with the receipt attached";
                      const proof =
                        body.proofIncluded === false ? " Telnyx details were unavailable, so the proof table was left out." : "";
                      return `Fax confirmation resent to ${to} ${receipt}.${proof}`;
                    });
                  } finally {
                    setResendingFaxConfirmation(false);
                  }
                }}
                tooltip={
                  !userEmail
                    ? "No customer email on file"
                    : hasFaxReceipt
                      ? `Re-sends the "delivered to the IRS" email to ${userEmail} with the IRS fax transmission receipt PDF attached.`
                      : `Re-sends the "delivered to the IRS" email to ${userEmail}. No receipt PDF is on file, so it goes without an attachment.`
                }
              >
                {resendingFaxConfirmation ? "Resending fax confirmation…" : "Resend fax confirmation"}
              </ActionButton>
            )}
        </div>
      </div>

      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">PDFs</p>
        <div className="flex flex-wrap items-center gap-2">
            {/* Quick preview link — opens the current unsigned PDF in a new
                tab. Uses the admin-auth endpoint with Cache-Control: no-store
                so a regen always shows the latest bytes (no stale CDN copy). */}
            <a
              href={`/api/admin/filings/${filingId}/pdf?t=${Date.now()}`}
              target="_blank"
              rel="noopener"
              aria-disabled={!hasGeneratedPdf}
              onClick={(e) => {
                if (!hasGeneratedPdf) e.preventDefault();
              }}
              className={`inline-flex items-center px-3 py-1.5 text-sm rounded-md border transition-colors ${
                hasGeneratedPdf
                  ? "border-accent text-accent bg-accent/5 hover:bg-accent/10"
                  : "border-slate-200 bg-slate-50 text-slate-300 cursor-not-allowed"
              }`}
              title={hasGeneratedPdf ? "Opens the current unsigned PDF in a new tab" : "Generate the PDF first"}
            >
              View unsigned PDF ↗
            </a>
            {hasSignedPdf && (
              <a
                href={`/api/admin/filings/${filingId}/pdf?signed=1&t=${Date.now()}`}
                target="_blank"
                rel="noopener"
                className="inline-flex items-center px-3 py-1.5 text-sm rounded-md border border-emerald-300 text-emerald-700 bg-emerald-50 hover:bg-emerald-100"
                title="Opens the signed PDF (what will be faxed to the IRS on next Send fax)"
              >
                View signed PDF ↗
              </a>
            )}
            {hasFaxedPdf && (
              <a
                href={`/api/admin/filings/${filingId}/pdf?faxed=1&t=${Date.now()}`}
                target="_blank"
                rel="noopener"
                className="inline-flex items-center px-3 py-1.5 text-sm rounded-md border border-slate-400 text-slate-700 bg-slate-50 hover:bg-slate-100"
                title={`Snapshot of the exact bytes faxed to the IRS${faxedAt ? ` at ${faxedAt}` : ""}`}
              >
                View faxed PDF ↗
              </a>
            )}
        </div>
      </div>

      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">Change the package</p>
        <div className="flex flex-wrap items-center gap-2">
            <ActionButton
              disabled={pending || uploading !== null}
              onClick={async () => {
                if (!(await confirmRegenerate())) return;
                await callApi({ action: "regeneratePdf" }, "PDF regenerated from current filing data");
              }}
              tooltip="Rebuilds the unsigned PDF from current filing fields. Use after editing fields by hand. Discards any existing signed PDF — customer must re-sign."
            >
              Regenerate PDF
            </ActionButton>
          <label>
              <span
                className={`inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-slate-300 bg-white ${
                  pending || uploading !== null ? "opacity-50 cursor-not-allowed" : "hover:bg-slate-50 cursor-pointer"
                }`}
              >
                {uploading === "reviewed"
                  ? "Uploading reviewed PDF…"
                  : notifyClient
                    ? "Upload reviewed PDF & send to client…"
                    : "Upload reviewed PDF (no email)…"}
              </span>
              <input
                type="file"
                accept="application/pdf,.pdf"
                disabled={pending || uploading !== null}
                onChange={(e) => {
                  const input = e.currentTarget;
                  const file = e.target.files?.[0];
                  void handleReviewedPdfUpload(file).finally(() => {
                    input.value = "";
                  });
                }}
                className="sr-only"
              />
          </label>
          <label className="inline-flex items-center gap-1.5 text-xs text-slate-600">
            <input
              type="checkbox"
              checked={notifyClient}
              onChange={(e) => setNotifyClient(e.target.checked)}
              disabled={pending || uploading !== null}
              className="h-3.5 w-3.5 rounded border-slate-300"
            />
            Email the client to check and sign
          </label>
        </div>
        <p className="max-w-prose text-xs text-slate-400">
          Upload reviewed PDF: the client is emailed a magic link to check this exact file and sign it (or ask for a change). Untick &ldquo;Email the client&rdquo; to upload a new version quietly; it is still the version they sign in their portal. Any signature they drew on an earlier version is set aside, so they always sign the version that gets faxed.
        </p>
      </div>

      {msg && (
        <div
          className={`text-sm px-3 py-2 rounded-md ${
            msg.kind === "ok"
              ? "bg-emerald-50 text-emerald-800 border border-emerald-200"
              : "bg-red-50 text-red-800 border border-red-200"
          }`}
        >
          {msg.text}
        </div>
      )}
    </div>
  );
}

type ActionResponse =
  | { ok: true; payload: Record<string, unknown> }
  | { ok: false; message: string; code?: string };

// Must match MIN_REFAX_REASON_CHARS in lib/admin/filingActions.ts (not
// imported: that module is server-only). The server re-checks it anyway.
export const REFAX_MIN_REASON_CHARS = 10;

export function refaxReasonIsValid(reason: string): boolean {
  return reason.replace(/\s/g, "").length >= REFAX_MIN_REASON_CHARS;
}

// The admin route answers errors as { error, code }; older/other failures may
// be plain text or an HTML error page.
export function parseActionError(text: string, httpStatus: number): { message: string; code?: string } {
  try {
    const parsed = JSON.parse(text) as { error?: unknown; code?: unknown } | null;
    if (parsed && typeof parsed.error === "string" && parsed.error.trim()) {
      return {
        message: parsed.error,
        ...(typeof parsed.code === "string" ? { code: parsed.code } : {}),
      };
    }
  } catch {
    // not JSON — fall through
  }
  return { message: text.trim() && text.length <= 500 ? text.trim() : `HTTP ${httpStatus}` };
}

function ActionButton({
  children,
  onClick,
  disabled,
  tooltip,
  primary = false,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  tooltip?: string;
  primary?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={tooltip}
      className={`px-3 py-1.5 text-sm rounded-md disabled:opacity-50 disabled:cursor-not-allowed transition-colors ${
        primary
          ? "bg-accent text-white hover:bg-accent/90 font-medium px-4 py-2"
          : "border border-slate-300 bg-white hover:bg-slate-50"
      }`}
    >
      {children}
    </button>
  );
}

function formatUtc(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? iso : `${d.toISOString().slice(0, 16).replace("T", " ")} UTC`;
}
