"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Loader2 } from "lucide-react";

const STATUSES = [
  "DRAFT",
  "PAID",
  "PDF_GENERATED",
  "SIGNATURE_PENDING",
  "SIGNED_UPLOADED",
  "FAXED",
  "CONFIRMED",
  "FAILED",
];

type Props = {
  filingId: string;
  currentStatus: string;
  userEmail: string | null;
  hasFaxService: boolean;
  hasSignedPdf: boolean;
  hasGeneratedPdf: boolean;
  hasCustomerSignature: boolean;
  hasFaxedPdf: boolean;
  faxedAt: string | null; // ISO string when the fax was sent
};

export function AdminActions({ filingId, currentStatus, userEmail, hasFaxService, hasSignedPdf, hasGeneratedPdf, hasCustomerSignature, hasFaxedPdf, faxedAt }: Props) {
  // Confirm before discarding the signed PDF; regen invalidates it because
  // the signature was applied to the old PDF and won't be valid against the
  // freshly generated bytes.
  async function confirmRegenerate(): Promise<boolean> {
    if (!hasSignedPdf) return true;
    return window.confirm(
      "Regenerating will DISCARD the existing signed PDF — the customer (or you) will need to re-sign. Continue?",
    );
  }

  const router = useRouter();
  const [pending, startTransition] = useTransition();
  const [status, setStatus] = useState(currentStatus);
  const [msg, setMsg] = useState<{ kind: "ok" | "err"; text: string } | null>(null);

  async function callApi(body: Record<string, unknown>, okMsg: string) {
    setMsg(null);
    try {
      const res = await fetch(`/api/admin/filings/${filingId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const err = await res.text();
        setMsg({ kind: "err", text: err || `HTTP ${res.status}` });
        return;
      }
      setMsg({ kind: "ok", text: okMsg });
      startTransition(() => router.refresh());
    } catch (e) {
      setMsg({ kind: "err", text: e instanceof Error ? e.message : "Network error" });
    }
  }

  // Read a File object as base64 (no data: prefix) so we can post it as JSON.
  // PDFs are small enough (200KB-2MB typical) that this is fine without
  // multipart/streaming.
  function fileToBase64(file: File): Promise<string> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result;
        if (typeof result !== "string") return reject(new Error("Unexpected reader result"));
        const comma = result.indexOf(",");
        resolve(comma === -1 ? result : result.slice(comma + 1));
      };
      reader.onerror = () => reject(reader.error ?? new Error("Read failed"));
      reader.readAsDataURL(file);
    });
  }

  async function handleSignedPdfUpload(file: File | undefined) {
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".pdf")) {
      setMsg({ kind: "err", text: "Please pick a .pdf file." });
      return;
    }
    if (file.size > 10 * 1024 * 1024) {
      setMsg({ kind: "err", text: `File too large (${(file.size / 1024 / 1024).toFixed(1)} MB). Max 10 MB.` });
      return;
    }
    try {
      const pdfBase64 = await fileToBase64(file);
      await callApi(
        { action: "uploadSignedPdf", pdfBase64 },
        `Signed PDF uploaded (${(file.size / 1024).toFixed(0)} KB). Ready to fax.`,
      );
    } catch (e) {
      setMsg({ kind: "err", text: e instanceof Error ? e.message : "Upload failed" });
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row gap-2 sm:items-end">
        <label className="flex-1">
          <span className="block text-xs text-slate-500 mb-1">Override status</span>
          <select
            value={status}
            onChange={(e) => setStatus(e.target.value)}
            disabled={pending}
            className="w-full px-3 py-2 text-sm border border-slate-300 rounded-md bg-white"
          >
            {STATUSES.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </label>
        <button
          type="button"
          onClick={() => callApi({ action: "setStatus", status }, `Status set to ${status}`)}
          disabled={pending || status === currentStatus}
          className="px-4 py-2 text-sm font-medium bg-slate-900 text-white rounded-md hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : "Save"}
        </button>
      </div>

      {/* Sign the package — two paths, pick one:
          (1) In-app placement tool: drop the customer's drawn signature on
              the unsigned PDF via click-to-place. Only available if the
              customer drew their signature in the portal.
          (2) Upload externally-signed PDF: accountant signs offline (Adobe
              Acrobat, print + scan, etc.) and uploads the finished file. */}
      <div className="pt-2 border-t border-slate-100 space-y-2">
        <p className="text-xs text-slate-500">Sign the package</p>
        <div className="flex flex-wrap gap-2">
          {hasCustomerSignature ? (
            <a
              href={`/admin/filings/${filingId}/place-signature`}
              className="inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-accent bg-accent/5 text-accent hover:bg-accent/10"
            >
              Place customer signature →
            </a>
          ) : (
            <span
              title="Customer hasn't drawn their signature in the portal yet"
              className="inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-slate-200 bg-slate-50 text-slate-400 cursor-not-allowed"
            >
              Place customer signature → (no signature yet)
            </span>
          )}
          <label className="inline-flex items-center gap-2 px-3 py-1.5 text-sm rounded-md border border-slate-300 bg-white hover:bg-slate-50 cursor-pointer">
            <span>{hasSignedPdf ? "Replace with uploaded PDF…" : "Upload signed PDF…"}</span>
            <input
              type="file"
              accept="application/pdf,.pdf"
              disabled={pending}
              onChange={(e) => {
                const file = e.target.files?.[0];
                void handleSignedPdfUpload(file);
                e.target.value = ""; // reset so same file can be re-picked after error
              }}
              className="sr-only"
            />
          </label>
        </div>
        <p className="text-xs text-slate-400">
          Either path populates <code className="font-mono">signedPdfKey</code> + bumps status to{" "}
          <code className="font-mono">SIGNED_UPLOADED</code> so the fax button enables.
        </p>
      </div>

      {/* Send fax — primary action when signed PDF is ready */}
      {hasFaxService && (
        <div className="pt-2 border-t border-slate-100">
          <p className="text-xs text-slate-500 mb-2">Fax submission</p>
          <ActionButton
            disabled={pending || !hasSignedPdf}
            onClick={() => callApi({ action: "retryFax" }, "Fax submitted to IRS ✓")}
            tooltip={!hasSignedPdf ? "No signed PDF uploaded yet" : undefined}
            primary
          >
            {currentStatus === "FAXED" || currentStatus === "CONFIRMED" ? "Retry fax" : "Send fax to IRS"}
          </ActionButton>
          {!hasSignedPdf && (
            <p className="text-xs text-slate-400 mt-1">Waiting for customer to upload signed PDF</p>
          )}
        </div>
      )}

      <div className="flex flex-wrap gap-2 pt-2 border-t border-slate-100">
        <ActionButton
          disabled={pending || !userEmail}
          onClick={() => callApi({ action: "resendOrderConfirmation" }, "Order confirmation resent")}
          tooltip={!userEmail ? "No customer email on file" : undefined}
        >
          Resend order confirmation
        </ActionButton>
        <ActionButton
          disabled={pending || !userEmail}
          onClick={() => callApi({ action: "resendMagicLink" }, "Magic link resent")}
          tooltip={!userEmail ? "No customer email on file" : undefined}
        >
          Resend magic link
        </ActionButton>
        <ActionButton
          disabled={pending}
          onClick={async () => {
            if (!(await confirmRegenerate())) return;
            await callApi({ action: "regeneratePdf" }, "PDF regenerated from current filing data");
          }}
          tooltip="Rebuilds the unsigned PDF from current filing fields. Use after editing fields by hand. Discards any existing signed PDF — customer must re-sign."
        >
          Regenerate PDF
        </ActionButton>
        {/* Quick preview link — opens the current unsigned PDF in a new
            tab. Uses the admin-auth endpoint with Cache-Control: no-store
            so a regen always shows the latest bytes (no stale CDN copy). */}
        <a
          href={`/api/admin/filings/${filingId}/pdf?t=${Date.now()}`}
          target="_blank"
          rel="noopener"
          aria-disabled={!hasGeneratedPdf}
          onClick={(e) => {
            if (!hasGeneratedPdf) e.preventDefault();
          }}
          className={`px-3 py-1.5 text-sm rounded-md border transition-colors ${
            hasGeneratedPdf
              ? "border-accent text-accent bg-accent/5 hover:bg-accent/10"
              : "border-slate-200 bg-slate-50 text-slate-300 cursor-not-allowed"
          }`}
          title={hasGeneratedPdf ? "Opens the current unsigned PDF in a new tab" : "Generate the PDF first"}
        >
          View unsigned PDF ↗
        </a>
        {hasSignedPdf && (
          <a
            href={`/api/admin/filings/${filingId}/pdf?signed=1&t=${Date.now()}`}
            target="_blank"
            rel="noopener"
            className="px-3 py-1.5 text-sm rounded-md border border-emerald-300 text-emerald-700 bg-emerald-50 hover:bg-emerald-100"
            title="Opens the signed PDF (what will be faxed to the IRS on next Send fax)"
          >
            View signed PDF ↗
          </a>
        )}
        {hasFaxedPdf && (
          <a
            href={`/api/admin/filings/${filingId}/pdf?faxed=1&t=${Date.now()}`}
            target="_blank"
            rel="noopener"
            className="px-3 py-1.5 text-sm rounded-md border border-slate-400 text-slate-700 bg-slate-50 hover:bg-slate-100"
            title={`Snapshot of the exact bytes faxed to the IRS${faxedAt ? ` at ${faxedAt}` : ""}`}
          >
            View faxed PDF ↗
          </a>
        )}
      </div>

      {msg && (
        <div
          className={`text-sm px-3 py-2 rounded-md ${
            msg.kind === "ok"
              ? "bg-emerald-50 text-emerald-800 border border-emerald-200"
              : "bg-red-50 text-red-800 border border-red-200"
          }`}
        >
          {msg.text}
        </div>
      )}
    </div>
  );
}

function ActionButton({
  children,
  onClick,
  disabled,
  tooltip,
  primary = false,
}: {
  children: React.ReactNode;
  onClick: () => void;
  disabled?: boolean;
  tooltip?: string;
  primary?: boolean;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      disabled={disabled}
      title={tooltip}
      className={`px-3 py-1.5 text-sm rounded-md disabled:opacity-50 disabled:cursor-not-allowed transition-colors ${
        primary
          ? "bg-accent text-white hover:bg-accent/90 font-medium px-4 py-2"
          : "border border-slate-300 bg-white hover:bg-slate-50"
      }`}
    >
      {children}
    </button>
  );
}
