import { Logo } from "@/components/Logo";

// Crafted HTML rendition of the IRS fax-transmission receipt customers receive
// as proof of filing. Replaces the old flat 3840px PNG screenshot: it's sharp
// at any size, themeable, and — set entirely in the mono "artifact" face — it
// IS the signature element of the marketing site. Sample metadata only; no real
// customer data. The actual delivered receipt is generated by
// generateFaxReceiptPdf() at fax time.

const ROWS: Array<{ label: string; value: string; strong?: boolean }> = [
  { label: "Status", value: "DELIVERED", strong: true },
  { label: "To", value: "IRS — Ogden PIN Unit" },
  { label: "Fax", value: "+1-855-887-7737" },
  { label: "Forms", value: "Form 5472 · Pro forma 1120" },
  { label: "Pages", value: "6 of 6 transmitted" },
  { label: "Timestamp (UTC)", value: "2026-04-11 14:32:07" },
  { label: "Confirmation", value: "TX-9F3A7C21" },
];

export function FaxReceipt({ className = "" }: { className?: string }) {
  return (
    <div
      className={`relative rounded-b-xl bg-paper text-ink shadow-2xl shadow-ink/20 ring-1 ring-paper-edge ${className}`}
    >
      {/* Perforated top edge — the tear line of a printed transmission slip. */}
      <div
        aria-hidden
        className="h-3 w-full rounded-t-xl bg-paper"
        style={{
          backgroundImage:
            "radial-gradient(circle at 6px 0, transparent 0 5px, #fbfaf7 5px)",
          backgroundSize: "12px 12px",
          backgroundPosition: "0 -6px",
          backgroundRepeat: "repeat-x",
        }}
      />

      <div className="px-6 pb-6 pt-2 sm:px-8 sm:pb-8">
        {/* Masthead */}
        <div className="flex items-center justify-between border-b border-paper-edge pb-4">
          <div>
            <p className="font-mono text-[11px] uppercase tracking-[0.18em] text-ink/50">
              Fax transmission receipt
            </p>
            <p className="mt-1 font-serif text-lg font-semibold text-ink">
              Proof of filing
            </p>
          </div>
          <Logo className="h-7 w-auto" />
        </div>

        {/* Metadata rows — the actual transmission record, in mono. */}
        <dl className="mt-5 space-y-3 font-mono text-[13px]">
          {ROWS.map((r) => (
            <div key={r.label} className="flex items-baseline justify-between gap-4">
              <dt className="whitespace-nowrap text-ink/45 uppercase tracking-wide text-[11px]">
                {r.label}
              </dt>
              <dd
                className={`flex items-center gap-1.5 text-right ${
                  r.strong ? "font-semibold text-emerald-700" : "text-ink"
                }`}
              >
                {r.strong && (
                  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" aria-hidden>
                    <path
                      d="M20 6 9 17l-5-5"
                      stroke="currentColor"
                      strokeWidth="3"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                )}
                {r.value}
              </dd>
            </div>
          ))}
        </dl>

        {/* Legal footer line — right padding keeps text clear of the stamp. */}
        <p className="mt-5 border-t border-paper-edge pt-4 pr-28 font-mono text-[11px] leading-relaxed text-ink/50">
          Filed under IRC § 6038A. Retain as proof of timely filing.
        </p>
      </div>

      {/* Official "TRANSMISSION OK" stamp — the one warm/brass accent. */}
      <div
        aria-hidden
        className="pointer-events-none absolute bottom-5 right-5 -rotate-[8deg] select-none rounded-md border-2 border-seal/60 px-2.5 py-1 text-seal/80"
      >
        <span className="font-mono text-[10px] font-semibold uppercase tracking-[0.16em]">
          Transmission OK
        </span>
      </div>
    </div>
  );
}
